// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Axuiliary/About.vue')['default']
    ActionConfig: typeof import('./src/components/ActionConfig.vue')['default']
    ActionPopover: typeof import('./src/components/Action/ActionPopover.vue')['default']
    AuxiliaryConfig: typeof import('./src/components/AuxiliaryConfig.vue')['default']
    BackgroundFilterSelector: typeof import('./src/components/FormControl/BackgroundFilterSelector.vue')['default']
    BackgroundImage: typeof import('./src/components/Global/BackgroundImage.vue')['default']
    BackgroundSelector: typeof import('./src/components/FormControl/BackgroundSelector.vue')['default']
    BaseConfig: typeof import('./src/components/BaseConfig.vue')['default']
    ChangeLog: typeof import('./src/components/Axuiliary/ChangeLog.vue')['default']
    CleanCache: typeof import('./src/components/Axuiliary/CleanCache.vue')['default']
    ComponentConfig: typeof import('./src/components/ComponentConfig.vue')['default']
    DefaultTheme: typeof import('./src/components/Global/DefaultTheme.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FAQ: typeof import('./src/components/Axuiliary/FAQ.vue')['default']
    FontSelector: typeof import('./src/components/FormControl/FontSelector.vue')['default']
    GlobalConfig: typeof import('./src/components/GlobalConfig.vue')['default']
    GooeyMenu: typeof import('./src/components/GooeyMenu.vue')['default']
    ImportExport: typeof import('./src/components/Axuiliary/ImportExport.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Loading: typeof import('./src/components/Tools/Loading.vue')['default']
    MaterialSelector: typeof import('./src/components/FormControl/MaterialSelector.vue')['default']
    RecommendPicture: typeof import('./src/components/Recommend/RecommendPicture.vue')['default']
    RecommendVideo: typeof import('./src/components/Recommend/RecommendVideo.vue')['default']
    StandardColorPicker: typeof import('./src/components/FormControl/StandardColorPicker.vue')['default']
    TabCarousel: typeof import('./src/components/Global/TabCarousel.vue')['default']
    TabControl: typeof import('./src/components/Axuiliary/TabControl.vue')['default']
    Tips: typeof import('./src/components/Tools/Tips.vue')['default']
    Unset: typeof import('./src/components/Tools/Unset.vue')['default']
    WarnLock: typeof import('./src/components/FormControl/WarnLock.vue')['default']
  }
}

export { }
